package com.overbyte.gryphon.generator

import com.overbyte.gryphon.entity.Address
import com.overbyte.gryphon.enumerations.StateAbbreviation
import kotlin.random.Random

object AddressGenerator {
    val random = Random(System.currentTimeMillis())

    fun next(): Address {
        return Address().apply {
            addressLine1 = nextStreet
            city = nextCity
            state = nextState
            zipCode = nextZip
        }
    }

    private val nextStreet
        get() = "$streetPrefix $streetName ${streetSuffix[random.nextInt(streetSuffix.count())]}"

    private val streetPrefix: Int
        get() = random.nextInt(6000)

    private val streetName: String
        get() = streetNames[random.nextInt(streetNames.count())]

    private val nextCity: String
        get() = cities[random.nextInt(cities.count())]

    private val nextState: StateAbbreviation
        get() {
            val abbreviations = StateAbbreviation.values()
            return abbreviations[random.nextInt(abbreviations.size)]
        }

    private val nextZip: String
    get() = "${random.nextInt(10000, 99999)}"

    private val streetSuffix = listOf(
        "Avenue",
        "Way",
        "Street",
        "Circle",
        "Lane",
        "Boulevard"
    )

    private val streetNames = setOf(
        "HAWTHORNE",
        "INDOOROOPILLY",
        "CHERMSIDE",
        "UPPER MOUNT GRAVATT",
        "WAVELL HEIGHTS",
        "TINGALPA",
        "TAIGUM",
        "FOREST LAKE",
        "ALBION",
        "BOWEN HILLS",
        "HOLLAND PARK",
        "ASCOT",
        "CAMP HILL",
        "HAMILTON",
        "NEW FARM",
        "WAVELL HEIGHTS",
        "MOUNT OMMANEY",
        "MOOROOKA",
        "CALAMVALE",
        "INALA",
        "RUNCORN",
        "ROCKLEA",
        "TENERIFFE",
        "DARRA",
        "THE GAP",
        "KURABY",
        "BOONDALL",
        "MANLY WEST",
        "UPPER KEDRON",
        "GORDON PARK",
        "KENMORE",
        "KENMORE",
        "HERSTON",
        "GEEBUNG",
        "ALGESTER",
        "WOOLLOONGABBA",
        "MORNINGSIDE",
        "CARINDALE",
        "MOOROOKA",
        "RED HILL",
        "WILLAWONG",
        "NEWMARKET",
        "WILSTON",
        "NEWMARKET",
        "CHELMER",
        "GRACEVILLE",
        "NORTHGATE",
        "FITZGIBBON",
        "HOLLAND PARK WEST",
        "MOUNT CROSBY",
        "ASHGROVE",
        "SUNNYBANK HILLS",
        "KARAWATHA",
        "EAGLE FARM",
        "HEATHWOOD",
        "RICHLANDS",
        "DARRA",
        "RICHLANDS",
        "BARDON",
        "CARSELDINE",
        "CHAPEL HILL",
        "INALA",
        "NORMAN PARK",
        "ACACIA RIDGE",
        "KEDRON",
        "ALGESTER",
        "MACKENZIE",
        "FOREST LAKE",
        "ALGESTER",
        "SUNNYBANK",
        "MACGREGOR",
        "WACOL",
        "ACACIA RIDGE",
        "ASHGROVE",
        "KENMORE",
        "COOPERS PLAINS",
        "PADDINGTON",
        "TARINGA",
        "TOOWONG",
        "WILSTON",
        "WINDSOR",
        "BALD HILLS",
        "WYNNUM",
        "DEAGON",
        "WOOLOOWIN",
        "RUNCORN",
        "BROOKFIELD",
        "BULIMBA",
        "GRACEVILLE",
        "RED HILL",
        "WINDSOR",
        "BRISBANE CITY",
        "CARINA",
        "CLAYFIELD",
        "WEST END",
        "CLAYFIELD",
        "KEDRON",
        "DURACK",
        "NEW FARM",
        "ALBION",
        "CLAYFIELD",
        "NORMAN PARK",
        "SUNNYBANK HILLS",
        "MORNINGSIDE",
        "CARINDALE",
        "MURARRIE",
        "WISHART",
        "INALA",
        "STAFFORD HEIGHTS",
        "WISHART",
        "MANLY WEST",
        "TARINGA",
        "KENMORE HILLS",
        "KURABY",
        "JAMBOREE HEIGHTS",
        "SEVEN HILLS",
        "CANNON HILL",
        "COOPERS PLAINS",
        "ROBERTSON",
        "ALDERLEY",
        "PADDINGTON",
        "CAMP HILL",
        "FOREST LAKE",
        "WISHART",
        "RUNCORN",
        "UPPER MOUNT GRAVATT",
        "GRANGE",
        "FIG TREE POCKET",
        "ACACIA RIDGE",
        "ALBION",
        "AUCHENFLOWER",
        "FORTITUDE VALLEY",
        "HOLLAND PARK WEST",
        "MORNINGSIDE",
        "SHORNCLIFFE",
        "SUNNYBANK",
        "WOOLLOONGABBA",
        "WYNNUM",
        "ASPLEY",
        "MORNINGSIDE",
        "NORMAN PARK",
        "SANDGATE",
        "SEVEN HILLS",
        "DOOLANDELLA",
        "CARINDALE",
        "CORINDA",
        "ASPLEY",
        "SALISBURY",
        "CHERMSIDE WEST",
        "ALDERLEY",
        "SALISBURY",
        "HOLLAND PARK WEST",
        "BALD HILLS",
        "SALISBURY",
        "PULLENVALE",
        "BRISBANE AIRPORT",
        "DURACK",
        "WACOL",
        "MOGGILL",
        "ASHGROVE",
        "ALGESTER",
        "CAMP HILL",
        "DURACK",
    ).map { item ->
        item.split(" ").map { s -> s.lowercase().capitalize() }.joinToString(" ")
    }

    private val cities = listOf(
        "Castle Pines Village",
        "Todd Creek",
        "Basalt",
        "Monte Vista",
        "Florence",
        "Genesee",
        "Rocky Ford",
        "Meridian",
        "Ponderosa Park",
        "Yuma",
        "Bennett",
        "Orchard City",
        "Lincoln Park",
        "Silt",
        "Frisco",
        "Acres Green",
        "Burlington",
        "Palmer Lake",
        "Leadville",
        "Penrose",
        "Strasburg",
        "Walsenburg",
        "Buena Vista",
        "Hudson",
        "Holly Hills",
        "Palisade",
        "Platteville",
        "Bayfield",
        "Laporte",
        "Wray",
        "Cedaredge",
        "La Salle",
        "Coal Creek",
        "Rangely",
        "Meeker",
        "Granby",
        "Pagosa Springs",
        "Holyoke",
        "Center",
        "Lyons",
        "Las Animas	",
        "Limon",
        "Hayden",
        "Perry Park",
        "Ault",
        "Elizabeth",
        "Olathe",
        "Akron",
        "Kersey",
        "Del Norte",
        "Inverness",
        "Kremmling",
        "Columbine Valley",
        "Nederland",
        "Wiggins",
        "Paonia",
        "Mancos",
        "Aristocrat Ranchettes",
        "Mountain Village",
        "Indian Hills",
        "Aetna Estates",
        "Fraser",
        "Springfield",
        "Byers",
        "Keenesburg",
        "Cascade Park",
        "Georgetown",
        "Minturn",
        "Towaoc",
        "Pierce",
        "Fowler",
        "Julesburg",
        "Parachute",
        "Ridgeway",
        "Floyd Hill",
        "Gilcrest",
    )
}
