ALTER TABLE person
    ALTER COLUMN gender TYPE VARCHAR(255) USING (gender::VARCHAR(255));

ALTER TABLE person
    ALTER COLUMN state TYPE VARCHAR(255) USING (state::VARCHAR(255));

ALTER TABLE store
    ALTER COLUMN state TYPE VARCHAR(255) USING (state::VARCHAR(255));